services:
  tfa:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - maria
    entrypoint: tfa
  maria:
    image: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: tfa
      MYSQL_ROOT_PASSWORD: pwd
